version: "3"
services:
  app:
    container_name: rest-api-docker
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - redis
  
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'