version: '3.5'

services:
  redis:
      image: redis
  worker:
      build: ./worker
      command: npm start
      ports:
        - "6379:6379"
      volumes: 
          - ./worker/:/worker/
          - /worker/node_modules
      links: 
        - redis
  app:
      image: react-app
      ports:
        - "3000:3000"
      networks: 
        - webnet
      environment:
        DB_HOST: db
        REDIS_USER: redis
networks: 
  webnet:
              
